# Airflow version to be installed
airflow_version: "2.7.3"

# Python version for the project
python_version: "3.8.18"

# Path to a virtual evn
mode:
  virtualenv:
    venv_path: "C:\Users\5300\Desktop\autochek\question_two_batch_data_pipeline\airflow/.venv"

# Airflow connections
connections:
    # Example connection
    # - conn_id: example
    #   conn_type: http
    #   host: http://example.com
    #   port: 80
    #   login: user
    #   password: pass
    #   schema: http
    #   extra:
    #      example_extra_field: example-value

# Airflow variables
variables:
    # Example variable
    # - key: example
    #   value: example-value
    #   description: example-description